In [1]:
import numpy as np
import pandas as pd

In [2]:
bank = pd.read_csv(r"C:\Users\Safiya\Downloads\Anaconda Codes\bank.csv")
bank

age          job  marital  education default  balance housing loan  \
0       59       admin.  married  secondary      no     2343     yes   no   
1       56       admin.  married  secondary      no       45      no   no   
2       41   technician  married  secondary      no     1270     yes   no   
3       55     services  married  secondary      no     2476     yes   no   
4       54       admin.  married   tertiary      no      184      no   no   
...    ...          ...      ...        ...     ...      ...     ...  ...   
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         yes  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]

In [3]:
bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        11162 non-null  int64 
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64 
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64 
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64 
 12  campaign   11162 non-null  int64 
 13  pdays      11162 non-null  int64 
 14  previous   11162 non-null  int64 
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [4]:
#Handling null values
bank.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

* There are no null values.


In [5]:
#Splitting data into x and y
x = bank.iloc[:, 0:16].values
y = bank.iloc[:, 16:17].values

In [6]:
x

array([[59, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [56, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [41, 'technician', 'married', ..., -1, 0, 'unknown'],
       ...,
       [32, 'technician', 'single', ..., -1, 0, 'unknown'],
       [43, 'technician', 'married', ..., 172, 5, 'failure'],
       [34, 'technician', 'married', ..., -1, 0, 'unknown']], dtype=object)

In [7]:
y

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [9]:
ct = ColumnTransformer([("one",OneHotEncoder(),[1,2,3,4,6,7,8,10,15])],remainder = "passthrough")
x = ct.fit_transform(x)

In [10]:
x

array([[1.0, 0.0, 0.0, ..., 1, -1, 0],
       [1.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 0.0, 0.0, ..., 1, -1, 0],
       ...,
       [0.0, 0.0, 0.0, ..., 2, -1, 0],
       [0.0, 0.0, 0.0, ..., 2, 172, 5],
       [0.0, 0.0, 0.0, ..., 1, -1, 0]], dtype=object)

In [11]:
ct1 = ColumnTransformer([('one', OneHotEncoder(), [0])], remainder = 'passthrough')
y= ct1.fit_transform(y)

In [12]:
y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [13]:
x.shape

(11162, 51)

In [14]:
y.shape

(11162, 2)

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2,random_state = 0)

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [18]:
from tensorflow.keras.models import Sequential 

from tensorflow.keras.layers import Dense

In [19]:
categ = Sequential()

In [20]:
x_train.shape

(8929, 51)

In [21]:
y_train.shape

(8929, 2)

In [22]:
#Input Layer
categ.add(Dense(units = 51, kernel_initializer = "random_uniform", activation = "relu"))

In [23]:
#Hidden Layer1
categ.add(Dense(units = 102, kernel_initializer = "random_uniform", activation = "relu"))

In [24]:
#Hidden Layer2
categ.add(Dense(units = 102, kernel_initializer = "random_uniform", activation = "relu"))

In [25]:
#Output Layer
categ.add(Dense(units = 2, kernel_initializer = "random_uniform", activation = "softmax"))

In [26]:
categ.compile(optimizer = "rmsprop", loss = "categorical_crossentropy", metrics = ["accuracy"]) 

In [27]:
categ.fit(x_train, y_train, epochs = 500)

Epoch 1/500
280/280 [==============================] - 0s 456us/step - loss: 0.4162 - accuracy: 0.8160
Epoch 2/500
280/280 [==============================] - 0s 438us/step - loss: 0.3622 - accuracy: 0.8475
Epoch 3/500
280/280 [==============================] - 0s 438us/step - loss: 0.3468 - accuracy: 0.8562
Epoch 4/500
280/280 [==============================] - 0s 435us/step - loss: 0.3382 - accuracy: 0.8593
Epoch 5/500
280/280 [==============================] - 0s 431us/step - loss: 0.3299 - accuracy: 0.8657
Epoch 6/500
280/280 [==============================] - 0s 435us/step - loss: 0.3218 - accuracy: 0.8687
Epoch 7/500
280/280 [==============================] - 0s 431us/step - loss: 0.3165 - accuracy: 0.8729
Epoch 8/500
280/280 [==============================] - 0s 435us/step - loss: 0.3134 - accuracy: 0.8726
Epoch 9/500
280/280 [==============================] - 0s 435us/step - loss: 0.3062 - accuracy: 0.8759
Epoch 10/500
280/280 [==============================] - 0s 431us/step - l

280/280 [==============================] - 0s 431us/step - loss: 0.1118 - accuracy: 0.9562
Epoch 80/500
280/280 [==============================] - 0s 432us/step - loss: 0.1085 - accuracy: 0.9553
Epoch 81/500
280/280 [==============================] - 0s 431us/step - loss: 0.1056 - accuracy: 0.9599
Epoch 82/500
280/280 [==============================] - 0s 442us/step - loss: 0.1043 - accuracy: 0.9579
Epoch 83/500
280/280 [==============================] - 0s 445us/step - loss: 0.1063 - accuracy: 0.9599
Epoch 84/500
280/280 [==============================] - 0s 442us/step - loss: 0.1018 - accuracy: 0.9624
Epoch 85/500
280/280 [==============================] - 0s 435us/step - loss: 0.1036 - accuracy: 0.9597
Epoch 86/500
280/280 [==============================] - 0s 435us/step - loss: 0.0983 - accuracy: 0.9619
Epoch 87/500
280/280 [==============================] - 0s 431us/step - loss: 0.0959 - accuracy: 0.9627
Epoch 88/500
280/280 [==============================] - 0s 431us/step - loss:

280/280 [==============================] - 0s 429us/step - loss: 0.0506 - accuracy: 0.9854
Epoch 158/500
280/280 [==============================] - 0s 445us/step - loss: 0.0450 - accuracy: 0.9866
Epoch 159/500
280/280 [==============================] - 0s 442us/step - loss: 0.0412 - accuracy: 0.9870
Epoch 160/500
280/280 [==============================] - 0s 435us/step - loss: 0.0418 - accuracy: 0.9881
Epoch 161/500
280/280 [==============================] - 0s 399us/step - loss: 0.0455 - accuracy: 0.9866
Epoch 162/500
280/280 [==============================] - 0s 414us/step - loss: 0.0390 - accuracy: 0.9890
Epoch 163/500
280/280 [==============================] - 0s 402us/step - loss: 0.0408 - accuracy: 0.9872
Epoch 164/500
280/280 [==============================] - 0s 452us/step - loss: 0.0408 - accuracy: 0.9866
Epoch 165/500
280/280 [==============================] - 0s 451us/step - loss: 0.0390 - accuracy: 0.9862
Epoch 166/500
280/280 [==============================] - 0s 452us/ste

280/280 [==============================] - 0s 433us/step - loss: 0.0267 - accuracy: 0.9929
Epoch 236/500
280/280 [==============================] - 0s 435us/step - loss: 0.0349 - accuracy: 0.9913
Epoch 237/500
280/280 [==============================] - 0s 435us/step - loss: 0.0226 - accuracy: 0.9940
Epoch 238/500
280/280 [==============================] - 0s 422us/step - loss: 0.0278 - accuracy: 0.9929
Epoch 239/500
280/280 [==============================] - 0s 442us/step - loss: 0.0248 - accuracy: 0.9938
Epoch 240/500
280/280 [==============================] - 0s 435us/step - loss: 0.0227 - accuracy: 0.9938
Epoch 241/500
280/280 [==============================] - 0s 438us/step - loss: 0.0282 - accuracy: 0.9925
Epoch 242/500
280/280 [==============================] - 0s 452us/step - loss: 0.0310 - accuracy: 0.9924
Epoch 243/500
280/280 [==============================] - 0s 517us/step - loss: 0.0235 - accuracy: 0.9933
Epoch 244/500
280/280 [==============================] - 0s 458us/ste

280/280 [==============================] - 0s 423us/step - loss: 0.0133 - accuracy: 0.9956
Epoch 314/500
280/280 [==============================] - 0s 424us/step - loss: 0.0229 - accuracy: 0.9956
Epoch 315/500
280/280 [==============================] - 0s 426us/step - loss: 0.0235 - accuracy: 0.9941
Epoch 316/500
280/280 [==============================] - 0s 390us/step - loss: 0.0130 - accuracy: 0.9959
Epoch 317/500
280/280 [==============================] - 0s 417us/step - loss: 0.0188 - accuracy: 0.9947
Epoch 318/500
280/280 [==============================] - 0s 385us/step - loss: 0.0204 - accuracy: 0.9952
Epoch 319/500
280/280 [==============================] - 0s 422us/step - loss: 0.0241 - accuracy: 0.9948
Epoch 320/500
280/280 [==============================] - 0s 455us/step - loss: 0.0200 - accuracy: 0.9950
Epoch 321/500
280/280 [==============================] - 0s 404us/step - loss: 0.0219 - accuracy: 0.9947
Epoch 322/500
280/280 [==============================] - 0s 422us/ste

280/280 [==============================] - 0s 435us/step - loss: 0.0306 - accuracy: 0.9951
Epoch 392/500
280/280 [==============================] - 0s 431us/step - loss: 0.0174 - accuracy: 0.9954
Epoch 393/500
280/280 [==============================] - 0s 431us/step - loss: 0.0237 - accuracy: 0.9951
Epoch 394/500
280/280 [==============================] - 0s 431us/step - loss: 0.0216 - accuracy: 0.9952
Epoch 395/500
280/280 [==============================] - 0s 438us/step - loss: 0.0234 - accuracy: 0.9948
Epoch 396/500
280/280 [==============================] - 0s 435us/step - loss: 0.0192 - accuracy: 0.9955
Epoch 397/500
280/280 [==============================] - 0s 442us/step - loss: 0.0107 - accuracy: 0.9970
Epoch 398/500
280/280 [==============================] - 0s 435us/step - loss: 0.0129 - accuracy: 0.9969
Epoch 399/500
280/280 [==============================] - 0s 431us/step - loss: 0.0204 - accuracy: 0.9957
Epoch 400/500
280/280 [==============================] - 0s 435us/ste

280/280 [==============================] - 0s 386us/step - loss: 0.0259 - accuracy: 0.9962
Epoch 470/500
280/280 [==============================] - 0s 427us/step - loss: 0.0264 - accuracy: 0.9952
Epoch 471/500
280/280 [==============================] - 0s 381us/step - loss: 0.0181 - accuracy: 0.9974
Epoch 472/500
280/280 [==============================] - 0s 430us/step - loss: 0.0255 - accuracy: 0.9941
Epoch 473/500
280/280 [==============================] - 0s 426us/step - loss: 0.0365 - accuracy: 0.9945
Epoch 474/500
280/280 [==============================] - 0s 427us/step - loss: 0.0102 - accuracy: 0.9971
Epoch 475/500
280/280 [==============================] - 0s 428us/step - loss: 0.0202 - accuracy: 0.9960
Epoch 476/500
280/280 [==============================] - 0s 428us/step - loss: 0.0169 - accuracy: 0.9971
Epoch 477/500
280/280 [==============================] - 0s 426us/step - loss: 0.0144 - accuracy: 0.9975
Epoch 478/500
280/280 [==============================] - 0s 422us/ste

In [28]:
y_predict = categ.predict(x_test)


In [29]:
y_predict

array([[1.0000000e+00, 7.9365007e-37],
       [0.0000000e+00, 1.0000000e+00],
       [1.0000000e+00, 0.0000000e+00],
       ...,
       [7.6131172e-02, 9.2386883e-01],
       [1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 5.9514804e-26]], dtype=float32)

In [30]:
bank.head(1)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes

In [32]:
yp =categ.predict(sc.transform(ct.transform([[43, "services", "married", "secondary", "yes", 2343, "yes", "no", "unknown", 8, "may", 1042, 1, -1, 0, "unknown"]])))

In [52]:
deposit = ["no","yes"]
prediction = deposit[np.argmax(yp)]

In [53]:
prediction

'yes'

In [54]:
yp =categ.predict(sc.transform(ct.transform([[26, "services", "single", "secondary", "no", 5265, "yes", "no", "unknown", 2, "may", 249, 1, -1, 0, "unknown"]])))

In [55]:
prediction = deposit[np.argmax(yp)]

In [56]:
prediction

'no'

In [61]:
bank.tail(5)

age          job  marital  education default  balance housing loan  \
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no

In [65]:
yp =categ.predict(sc.transform(ct.transform([[45, "blue-collar", "married", "secondary", "no", 769, "no", "no", "unknown", 14, "jun", 75, 4, -1, 0, "unknown"]])))

In [66]:
prediction = deposit[np.argmax(yp)]

In [67]:
prediction

'no'