In [1]:
import numpy as np
import pandas as pd

In [2]:
bank = pd.read_csv(r"C:\Users\Safiya\Downloads\Anaconda Codes\bank.csv")
bank

age          job  marital  education default  balance housing loan  \
0       59       admin.  married  secondary      no     2343     yes   no   
1       56       admin.  married  secondary      no       45      no   no   
2       41   technician  married  secondary      no     1270     yes   no   
3       55     services  married  secondary      no     2476     yes   no   
4       54       admin.  married   tertiary      no      184      no   no   
...    ...          ...      ...        ...     ...      ...     ...  ...   
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         yes  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]

In [3]:
bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        11162 non-null  int64 
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64 
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64 
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64 
 12  campaign   11162 non-null  int64 
 13  pdays      11162 non-null  int64 
 14  previous   11162 non-null  int64 
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [4]:
#Handling null values
bank.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

* There are no null values.


In [5]:
#Splitting data into x and y
x = bank.iloc[:, 0:16].values
y = bank.iloc[:, 16:17].values

In [6]:
x

array([[59, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [56, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [41, 'technician', 'married', ..., -1, 0, 'unknown'],
       ...,
       [32, 'technician', 'single', ..., -1, 0, 'unknown'],
       [43, 'technician', 'married', ..., 172, 5, 'failure'],
       [34, 'technician', 'married', ..., -1, 0, 'unknown']], dtype=object)

In [7]:
y

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [9]:
ct = ColumnTransformer([("one",OneHotEncoder(),[1,2,3,4,6,7,8,10,15])],remainder = "passthrough")
x = ct.fit_transform(x)

In [10]:
x

array([[1.0, 0.0, 0.0, ..., 1, -1, 0],
       [1.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 0.0, 0.0, ..., 1, -1, 0],
       ...,
       [0.0, 0.0, 0.0, ..., 2, -1, 0],
       [0.0, 0.0, 0.0, ..., 2, 172, 5],
       [0.0, 0.0, 0.0, ..., 1, -1, 0]], dtype=object)

In [11]:
ct1 = ColumnTransformer([('one', OneHotEncoder(), [0])], remainder = 'passthrough')
y= ct1.fit_transform(y)

In [12]:
y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [13]:
x.shape

(11162, 51)

In [14]:
y.shape

(11162, 2)

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2,random_state = 0)

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [18]:
from tensorflow.keras.models import Sequential 

from tensorflow.keras.layers import Dense

In [19]:
categ = Sequential()

In [20]:
x_train.shape

(8929, 51)

In [21]:
y_train.shape

(8929, 2)

In [22]:
#Input Layer
categ.add(Dense(units = 51, kernel_initializer = "random_uniform", activation = "relu"))

In [23]:
#Hidden Layer1
categ.add(Dense(units = 102, kernel_initializer = "random_uniform", activation = "relu"))

In [24]:
#Hidden Layer2
categ.add(Dense(units = 102, kernel_initializer = "random_uniform", activation = "relu"))

In [28]:
#Output Layer
categ.add(Dense(units = 2, kernel_initializer = "random_uniform", activation = "softmax"))

In [29]:
categ.compile(optimizer = "rmsprop", loss = "categorical_crossentropy", metrics = ["accuracy"]) 

In [30]:
categ.fit(x_train, y_train, epochs = 500)

Epoch 1/500
280/280 [==============================] - 0s 487us/step - loss: 0.6134 - accuracy: 0.7902
Epoch 2/500
280/280 [==============================] - 0s 451us/step - loss: 0.4966 - accuracy: 0.8407
Epoch 3/500
280/280 [==============================] - 0s 456us/step - loss: 0.4310 - accuracy: 0.8505
Epoch 4/500
280/280 [==============================] - 0s 459us/step - loss: 0.3946 - accuracy: 0.8553
Epoch 5/500
280/280 [==============================] - 0s 455us/step - loss: 0.3708 - accuracy: 0.8598
Epoch 6/500
280/280 [==============================] - 0s 462us/step - loss: 0.3558 - accuracy: 0.8649
Epoch 7/500
280/280 [==============================] - 0s 480us/step - loss: 0.3453 - accuracy: 0.8683
Epoch 8/500
280/280 [==============================] - 0s 451us/step - loss: 0.3383 - accuracy: 0.8708
Epoch 9/500
280/280 [==============================] - 0s 459us/step - loss: 0.3331 - accuracy: 0.8719
Epoch 10/500
280/280 [==============================] - 0s 455us/step - l

280/280 [==============================] - 0s 459us/step - loss: 0.1498 - accuracy: 0.9548
Epoch 80/500
280/280 [==============================] - 0s 455us/step - loss: 0.1504 - accuracy: 0.9537
Epoch 81/500
280/280 [==============================] - 0s 452us/step - loss: 0.1512 - accuracy: 0.9532
Epoch 82/500
280/280 [==============================] - 0s 449us/step - loss: 0.1466 - accuracy: 0.9570
Epoch 83/500
280/280 [==============================] - 0s 454us/step - loss: 0.1507 - accuracy: 0.9544
Epoch 84/500
280/280 [==============================] - 0s 451us/step - loss: 0.1442 - accuracy: 0.9569
Epoch 85/500
280/280 [==============================] - 0s 462us/step - loss: 0.1419 - accuracy: 0.9588
Epoch 86/500
280/280 [==============================] - 0s 452us/step - loss: 0.1407 - accuracy: 0.9588
Epoch 87/500
280/280 [==============================] - 0s 454us/step - loss: 0.1413 - accuracy: 0.9583
Epoch 88/500
280/280 [==============================] - 0s 454us/step - loss:

280/280 [==============================] - 0s 456us/step - loss: 0.1196 - accuracy: 0.9671
Epoch 158/500
280/280 [==============================] - 0s 455us/step - loss: 0.1203 - accuracy: 0.9675
Epoch 159/500
280/280 [==============================] - 0s 451us/step - loss: 0.1193 - accuracy: 0.9675
Epoch 160/500
280/280 [==============================] - 0s 458us/step - loss: 0.1141 - accuracy: 0.9692
Epoch 161/500
280/280 [==============================] - 0s 459us/step - loss: 0.1206 - accuracy: 0.9670
Epoch 162/500
280/280 [==============================] - 0s 451us/step - loss: 0.1219 - accuracy: 0.9671
Epoch 163/500
280/280 [==============================] - 0s 413us/step - loss: 0.1224 - accuracy: 0.9670
Epoch 164/500
280/280 [==============================] - 0s 494us/step - loss: 0.1243 - accuracy: 0.9663
Epoch 165/500
280/280 [==============================] - 0s 455us/step - loss: 0.1159 - accuracy: 0.9693
Epoch 166/500
280/280 [==============================] - 0s 463us/ste

280/280 [==============================] - 0s 456us/step - loss: 0.1145 - accuracy: 0.9701
Epoch 236/500
280/280 [==============================] - 0s 452us/step - loss: 0.1107 - accuracy: 0.9703
Epoch 237/500
280/280 [==============================] - 0s 456us/step - loss: 0.1139 - accuracy: 0.9698
Epoch 238/500
280/280 [==============================] - 0s 456us/step - loss: 0.1111 - accuracy: 0.9703
Epoch 239/500
280/280 [==============================] - 0s 452us/step - loss: 0.1119 - accuracy: 0.9701
Epoch 240/500
280/280 [==============================] - 0s 452us/step - loss: 0.1172 - accuracy: 0.9686
Epoch 241/500
280/280 [==============================] - 0s 459us/step - loss: 0.1109 - accuracy: 0.9704
Epoch 242/500
280/280 [==============================] - 0s 467us/step - loss: 0.1146 - accuracy: 0.9696
Epoch 243/500
280/280 [==============================] - 0s 459us/step - loss: 0.1105 - accuracy: 0.9707
Epoch 244/500
280/280 [==============================] - 0s 452us/ste

280/280 [==============================] - 0s 456us/step - loss: 0.1101 - accuracy: 0.9714
Epoch 314/500
280/280 [==============================] - 0s 467us/step - loss: 0.1141 - accuracy: 0.9699
Epoch 315/500
280/280 [==============================] - 0s 456us/step - loss: 0.1105 - accuracy: 0.9707
Epoch 316/500
280/280 [==============================] - 0s 463us/step - loss: 0.1103 - accuracy: 0.9710
Epoch 317/500
280/280 [==============================] - 0s 467us/step - loss: 0.1049 - accuracy: 0.9728
Epoch 318/500
280/280 [==============================] - 0s 456us/step - loss: 0.1080 - accuracy: 0.9718
Epoch 319/500
280/280 [==============================] - 0s 456us/step - loss: 0.1052 - accuracy: 0.9733
Epoch 320/500
280/280 [==============================] - 0s 459us/step - loss: 0.1066 - accuracy: 0.9724
Epoch 321/500
280/280 [==============================] - 0s 452us/step - loss: 0.1081 - accuracy: 0.9726
Epoch 322/500
280/280 [==============================] - 0s 456us/ste

280/280 [==============================] - 0s 456us/step - loss: 0.1089 - accuracy: 0.9714
Epoch 392/500
280/280 [==============================] - 0s 459us/step - loss: 0.1092 - accuracy: 0.9716
Epoch 393/500
280/280 [==============================] - 0s 459us/step - loss: 0.1085 - accuracy: 0.9719
Epoch 394/500
280/280 [==============================] - 0s 459us/step - loss: 0.1110 - accuracy: 0.9714
Epoch 395/500
280/280 [==============================] - 0s 456us/step - loss: 0.1058 - accuracy: 0.9721
Epoch 396/500
280/280 [==============================] - 0s 456us/step - loss: 0.1057 - accuracy: 0.9726
Epoch 397/500
280/280 [==============================] - 0s 456us/step - loss: 0.1051 - accuracy: 0.9730
Epoch 398/500
280/280 [==============================] - 0s 456us/step - loss: 0.1088 - accuracy: 0.9719
Epoch 399/500
280/280 [==============================] - 0s 456us/step - loss: 0.1080 - accuracy: 0.9723
Epoch 400/500
280/280 [==============================] - 0s 456us/ste

280/280 [==============================] - 0s 456us/step - loss: 0.1129 - accuracy: 0.9704
Epoch 470/500
280/280 [==============================] - 0s 452us/step - loss: 0.1061 - accuracy: 0.9727
Epoch 471/500
280/280 [==============================] - 0s 456us/step - loss: 0.1038 - accuracy: 0.9733
Epoch 472/500
280/280 [==============================] - 0s 456us/step - loss: 0.1033 - accuracy: 0.9732
Epoch 473/500
280/280 [==============================] - 0s 460us/step - loss: 0.1067 - accuracy: 0.9726
Epoch 474/500
280/280 [==============================] - 0s 452us/step - loss: 0.1111 - accuracy: 0.9712
Epoch 475/500
280/280 [==============================] - 0s 456us/step - loss: 0.1071 - accuracy: 0.9724
Epoch 476/500
280/280 [==============================] - 0s 456us/step - loss: 0.1040 - accuracy: 0.9728
Epoch 477/500
280/280 [==============================] - 0s 457us/step - loss: 0.1085 - accuracy: 0.9714
Epoch 478/500
280/280 [==============================] - 0s 455us/ste

In [31]:
y_predict = categ.predict(x_test)


In [32]:
y_predict

array([[0.9974778 , 0.00252215],
       [0.03653813, 0.9634619 ],
       [0.9974778 , 0.00252215],
       ...,
       [0.03653813, 0.9634619 ],
       [0.9974778 , 0.00252215],
       [0.9974778 , 0.00252215]], dtype=float32)

In [64]:
x[0]

array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0,
       0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 1.0, 59, 2343, 5, 1042, 1, -1, 0], dtype=object)

In [65]:
yp =categ.predict(sc.transform([[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0,
       0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 1.0, 87, 1466, 2, 7392, 1, -1, 0]]))

In [66]:
deposit = ["no","yes"]
prediction = deposit[np.argmax(yp)]

In [67]:
prediction

'yes'

In [68]:
x[11157]

array([0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0,
       0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 1.0, 33, 1, 20, 257, 1, -1, 0], dtype=object)

In [75]:
yp =categ.predict(sc.transform([[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0,
       0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 1.0, 23, 1, 33, 249, 1, -1, 0]]))

In [76]:
prediction = deposit[np.argmax(yp)]

In [77]:
prediction

'no'

In [78]:
yp =categ.predict(sc.transform([[1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0,
       0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       0.0, 0.0, 1.0, 0.0, 1.0, 54, 5, 84, 1684, 1, -1, 0]]))

In [79]:
prediction = deposit[np.argmax(yp)]

In [80]:
prediction

'yes'